# Generated by Django 5.0.2 on 2024-03-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.PositiveIntegerField(verbose_name="Номер версии"),
        ),
    ]
